# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
  TargetRubyVersion: 2.1

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: false
  #Previous: Enabled: true. 
  #Do we care? Only needed for supporting ruby 1.9. in 2.0+, utf is the default.

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'

#Note: Beginning of old .rubocop_todo.yml below this line.

# Offense count: 1
Metrics/AbcSize:
  Max: 22

# Offense count: 1
# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 37

# Offense count: 70
# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154

# Offense count: 2
# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 15

# Offense count: 1
# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

# Offense count: 13
Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/application_controller.rb'
    - 'app/controllers/chess_controller.rb'
    - 'app/controllers/users/omniauth_callbacks_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/chess_helper.rb'
    - 'app/helpers/omniauth_callbacks_helper.rb'
    - 'app/models/piece.rb'
    - 'app/models/user.rb'
    - 'db/migrate/20170127030419_devise_create_users.rb'
    - 'db/migrate/20170127212138_create_pieces.rb'
    - 'db/migrate/20170127212534_create_games.rb'
    - 'db/migrate/20170128025601_add_omniauth_to_users.rb'
    - 'db/migrate/20170128084839_add_name_image_to_users.rb'

# Offense count: 1
# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

# Offense count: 1
# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15
