# This is the configuration used to check the rubocop source code.

inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'db/schema.rb'
    - 'config/initializers/simple_form.rb'
  TargetRubyVersion: 2.1

Style/Encoding:
  EnforcedStyle: when_needed
  Enabled: false
  #Previous: Enabled: true. 
  #Do we care? Only needed for supporting ruby 1.9. in 2.0+, utf is the default.

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Metrics/BlockLength:
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
    - 'spec/**/*_spec.rb'

#Note: Beginning of old .rubocop_todo.yml below this line.

Metrics/AbcSize:
  Max: 60

# Configuration parameters: CountComments, ExcludedMethods.
Metrics/BlockLength:
  Max: 37

# Configuration parameters: AllowHeredoc, AllowURI, URISchemes, IgnoreCopDirectives, IgnoredPatterns.
# URISchemes: http, https
Metrics/LineLength:
  Max: 154

# Configuration parameters: CountComments.
Metrics/MethodLength:
  Max: 30

# Configuration parameters: EnforcedStyle, SupportedStyles.
# SupportedStyles: nested, compact
Style/ClassAndModuleChildren:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

Style/Documentation:
  Enabled: false

# Configuration parameters: MinBodyLength.
Style/GuardClause:
  Exclude:
    - 'app/controllers/users/omniauth_callbacks_controller.rb'

# Cop supports --auto-correct.
Style/NumericLiterals:
  MinDigits: 15
